export const States: Record<string, string> = {
  'new york': 'New York',
  'new jersey': 'New Jersey',
  'california': 'California',
  'washington': 'Washington',
  'michigan': 'Michigan',
  'florida': 'Florida',
  'illinois': 'Illinois',
  'louisiana': 'Louisiana',
  'massachusetts': 'MASSACHUSETTS',
  'pennsylvania': 'Pennsylvania',
  'georgia': 'Georgia',
  'texas': 'Texas',
  'colorado': 'Colorado',
  'tennessee': 'Tennessee',
  'connecticut': 'Connecticut',
  'ohio': 'Ohio',
  'north carolina': 'North Carolina',
  'indiana': 'Indiana',
  'wisconsin': 'Wisconsin',
  'maryland': 'Maryland',
  'arizona': 'Arizona',
  'virginia': 'Virginia',
  'mississippi': 'Mississippi',
  'south_carolina': 'South Carolina',
  'nevada': 'Nevada',
  'utah': 'Utah',
  'minnesota': 'Minnesota',
  'alabama': 'Alabama',
  'missouri': 'Missouri',
  'arkansas': 'Arkansas',
  'oregon': 'Oregon',
  'washington dc': 'District Of Columbia',
  'oklahoma': 'Oklahoma',
  'kentucky': 'Kentucky',
  'iowa': 'Iowa',
  'maine': 'Maine',
  'rhode island': 'Rhode Island',
  'new hampshire': 'New Hampshire',
  'delaware': 'Delaware',
  'kansas': 'Kansas',
  'new mexico': 'New Mexico',
  'vermont': 'Vermont',
  'idaho': 'Idaho',
  'hawaii': 'Hawaii',
  'nebraska': 'Nebraska',
  'montana': 'Montana',
  'alaska': 'Alaska',
  'south dakota': 'South Dakota',
  'wyoming': 'Wyoming',
  'north dakota': 'North Dakota',
  'west virginia': 'West Virginia',
  'guam': 'Guam',
  'puerto rico': 'Puerto Rico',
  'virgin islands': 'United States Virgin Islands'
};